## 			Misc Tools Message
string command 		#enable_all:   		Enables leds_subscriber
			#disable_all:  		Disables leds_subscriber
			
			#custom:		Enables functionalities according with the following parameters
			
string leds        #Enable, disable or Empty to not change state
string sonars      #Enable, disable or Empty to not change state
string touch      #Enable, disable or Empty to not change state
