## 			Motion Tools Message
string command 		#enable_all:   		Enables animation_subscriber and set_angles_subscriber
			#disable_all:  		Disables animation_subscriber and set_angles_subscriber
			
			#custom:		Enables functionalities according with the following parameters
			
string animation        #Enable, disable or Empty to not change state
string set_angles       #Enable, disable or Empty to not change state